### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by brachy84** [TheDarkDnKTv/NukepoweredUtils#15]
Chrashlog
(https://hastebin.com/lolubifuxe.rb)

[Newest] version of gregtech and nputils and crashes every time.

**Comment by brachy84** [comment]
Sorry, this issue is actually caused by greg additions reworked

**Comment by huneau** [comment]
Hi @brachy84,
Im the maintainer of the new rework of gtaddition.
GA and NPU are not compatible.
