### ISSUE TITLE
Impossible machine recipes ( Too high EU/t in recipes )

### ISSUE THREAD

**Issue by HonzaVinCZ** [TheDarkDnKTv/NukepoweredUtils#2]
Hello, 
one of our server modpack players noticed this problem with impossible machine recipe:

 1x Superconductor Wire requires 122 880 EU/t and that can't be done by any machine. Also, there are more recipes with the same problem.

Attaching screenshots:

![image](https://user-images.githubusercontent.com/29098779/72295068-1c1def80-3657-11ea-9c75-18d037de2929.png)

![image](https://user-images.githubusercontent.com/29098779/72295090-27711b00-3657-11ea-8365-370ef5652b48.png)

**Comment by TheDarkDnKTv** [comment]
If you need to have ZMP+ tiers you should enable in config
```
# Set this to true to enable ZPM and UV tiers of machines
        B:uselessTiers=true
```
