### ISSUE TITLE
[Request] CraftTweaker 2 Compability

### ISSUE THREAD

**Issue by HonzaVinCZ** [TheDarkDnKTv/NukepoweredUtils#3]
Hello,
I'd like to ask you to make NukepoweredUtils compatible with CraftTweaker 2. Actually it's not possible to add any recipes into NPU machines using GTCE and CT2 compatibility.

**Comment by TheDarkDnKTv** [comment]
What exactly do you mean? There is same CT support like was in GA. From available machines for recipes now: 

- circuit_assembler
- cluster_mill
- assembly_line
- cracker_unit
- disassembling_machine
- naquadah_reactor (fuels)

**Comment by HonzaVinCZ** [comment]
So if I use this:
`import mods.gregtech.recipe.RecipeMap;
val disassembling_machine = mods.gregtech.recipe.RecipeMap.getByName("disassembling_machine");`
It should work just fine? 

Also give me some contact please, so you can close this thread then, thank you.

**Comment by TheDarkDnKTv** [comment]
It should work, how Arch said. Otherwise wait for update, in new version it will be `import mods.nputils.recipe.RecipeMaps`
