### ISSUE TITLE
Missing Integrated Circuits in Assembler recipes

### ISSUE THREAD

**Issue by HonzaVinCZ** [TheDarkDnKTv/NukepoweredUtils#4]
Hello, TheDarkDnKTv. In our modpack, we have problem with NukepoweredUtils recipes that missing integrated circuit, for example NanoSuite. If you make recipe with 4 carbon plates, advanced circuit and battery for boots, you can't make same recipe for helmet and add more things to it because it'll craft boots instead. I didn't check it where all the integrated circuits are missing but it definitely missing in NanoSuite - actually uncraftable. Thank you in advance for fixing this.

**Comment by TheDarkDnKTv** [comment]
Will check it

**Comment by TheDarkDnKTv** [comment]
Fixed.
