### ISSUE TITLE
Impossible to craft Neutronium

### ISSUE THREAD

**Issue by HonzaVinCZ** [TheDarkDnKTv/NukepoweredUtils#5]
Hello, one of our server modpack players found this problem:
To craft superconductor wire, you need Neutronium pipe that can't be reached without T3 Fusion Reactor. Another problem is that if you want to craft T1 Fusion Computer you need Supeconductor Coil that is crafted of Neutronium pipes too.

The solution could be to place Niobium-Titanium pipes instead of the neutronium ones.

Here you can see neutronium pipe in the middle to craft superconductor wire
![image](https://user-images.githubusercontent.com/29098779/72603972-566ae380-391a-11ea-9a7d-9e77cced6646.png)

And here it is required Supeconductor Coil to craft T1 Fusion Computer
![image](https://user-images.githubusercontent.com/29098779/72603612-a4cbb280-3919-11ea-983d-646fa533a579.png)

Thank you in advance for fixing this.

**Comment by TheDarkDnKTv** [comment]
Before write an issue there, please be sure, what there is no second recipe... Superconducting heating coil have two different recipes, chech it.
