### ISSUE TITLE
All multy-block structures are not working

### ISSUE THREAD

**Issue by CobaltSystem67** [TheDarkDnKTv/NukepoweredUtils#7]
Hello! Thanks a lot for the amazing addon for GregTech:CE! But I had a problem 😒... I can't build any multi-block structure... can't build a fusion reactor (MK1, MK2, MK3 ), not a big turbine... nothing 😒 I tried hard, checking with WIKI and Videos but only thing I got was "Unvalid structure", other blocks and wires are working. Your addon is amazing but I can't use it as it doesn't work for me, I tried fixing NukepoweredUtils in the mod by setting "True" - to enable ZPM and UV tiers of machines, (as it was "False" before) but it didn't help! Please, help me if you can!
![Fusion Reactor MK3 GtCE](https://user-images.githubusercontent.com/60386805/73263855-8bace680-41e2-11ea-9f13-7a200d4f2a33.png)
![Invalid Structure Fusion Reactor MK3](https://user-images.githubusercontent.com/60386805/73263899-9ebfb680-41e2-11ea-9e40-e0860c13ee62.png)

**Comment by TheDarkDnKTv** [comment]
See how structure looks in JEI. Fusion computer now cannot be inside ring, only outside. Had same when started discovering GA.

**Comment by TheDarkDnKTv** [comment]
And as well there MUST be only LuV hatches/buses again see JEI...

**Comment by CobaltSystem67** [comment]
Thank you so much, you helped me a lot, I didn' know that Jei is working with your mod

**Comment by TheDarkDnKTv** [comment]
You always can ask me in GTCE discord group. (@TheDarkDnKTv)
